name: IOS Deployment
on:
  workflow_dispatch:
    inputs:
      artifact_upload:
        description: 'Upload to Artifact'
        required: false
        type: boolean

jobs:
  build_android:
    name: Building IOS 
    runs-on: macos-latest
    steps:

      - name: Cache Flutter
        id: flutterCache
        uses: actions/cache@v3
        with:
          path: /opt/
          key: ${{ runner.OS }}-fllutter-cache-1
          # restore-keys: |
          #   ${{ runner.OS }}-flutter-cache
      


      - name: Setup Flutter
        if: steps.flutterCache.outputs.cache-hit != 'true'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: 3.7.12
        
      - name: Setup Ruby
        if: steps.flutterCache.outputs.cache-hit != 'true'
        uses: ruby/setup-ruby@v1
        with:
            ruby-version: '3.0'
            bundler-cache: true

      - name: Setup Java
        if: steps.flutterCache.outputs.cache-hit != 'true'
        uses: actions/setup-java@v1
        with:
            java-version: 11
    
      - name: Check xcodebuild Version
        run: |
            which xcodebuild
            xcodebuild -version

      - uses: actions/checkout@v3
      - name: Checkout Source Code
        env:
          IOS_DISTRIBUTION_CERTIFICATE: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE }}
          IOS_CICD_POC_DISTRIBUTIONMOBILEPROVISION: ${{ secrets.IOS_CICD_POC_DISTRIBUTIONMOBILEPROVISION }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$IOS_DISTRIBUTION_CERTIFICATE" > ios/IOS_DISTRIBUTION_CERTIFICATE.asc
          echo "$IOS_CICD_POC_DISTRIBUTIONMOBILEPROVISION" > ios/IOS_CICD_POC_DISTRIBUTIONMOBILEPROVISION.asc
          gpg -d --passphrase $GPG_PASSPHRASE --batch ios/IOS_DISTRIBUTION_CERTIFICATE.asc > ios/IOS_DISTRIBUTION_CERTIFICATE.p12
          gpg -d --passphrase $GPG_PASSPHRASE --batch ios/IOS_CICD_POC_DISTRIBUTIONMOBILEPROVISION.asc > ios/IOS_CICD_POC_DISTRIBUTIONMOBILEPROVISION.mobileprovision


          CERTIFICATE_PATH=`pwd`/ios/IOS_DISTRIBUTION_CERTIFICATE.p12
          PP_PATH=`pwd`/ios/IOS_CICD_POC_DISTRIBUTIONMOBILEPROVISION.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo "$CERTIFICATE_PATH"

          security create-keychain -p "$GPG_PASSPHRASE" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$GPG_PASSPHRASE" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$GPG_PASSPHRASE" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

          ls -la ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build IPA
        working-directory: ./ios
        run: |
          EXPORT_OPTION=`pwd`/exportOptions.plist
          echo "$EXPORT_OPTION"
          flutter build ipa --export-options-plist=/Users/runner/work/cicdpoc/cicdpoc/ios/exportOptions.plist

      - uses: actions/upload-artifact@v4
        with:
           name: ios-build
           path: |
            build/ios/
