name: FAD deployment
on:
  push:
    branches:
      - main
jobs:
  build_android:
    name: Building Android 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout Code
        env:
          KEYPROPERTIES: ${{ secrets.KEYPROPERTIES }}
          STOREFILE: ${{ secrets.STOREFILE }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
         gpg --version
         echo $KEYPROPERTIES > android/key.properties.asc
         echo $STOREFILE > android/keystorefile.jks.asc
         ls -la android

      - uses: actions/upload-artifact@v4
        with:
           name: my-artifact
           path: |
            android/key.properties.asc
            android/keystorefile.jks.asc

    #   - name: Setup Flutter
    #     uses: subosito/flutter-action@v1
    #     with:
    #       flutter-version: 3.7.12
        
    #   - name: Run Ruby
    #     uses: ruby/setup-ruby@v1
    #     with:
    #         ruby-version: '3.0'
    #         bundler-cache: true
  
    #   - name: Install Flutter dependencies
    #     run: flutter pub get

    #   - name: Setup Fastlane
    #     working-directory: ./android
    #     run: bundle install

    #   - name: Setup Java
    #     uses: actions/setup-java@v1
    #     with:
    #       java-version: 11

    #   - name: JAVA Command
    #     run: which java

    #   - name: JAVA Command
    #     run: echo $JAVA_HOME

    #   - name: Pwd Command
    #     run: ls -la android
  
    #   - name: Run Fastlane
    #     working-directory: ./android
    #     run: bundle exec fastlane beta
    #     # uses: maierj/fastlane-action@v3.0.0
    #     # with:
    #     #     lane: 'beta'
    #     #     subdirectory: android
    # #   - name: Build the APK
    # #     run: flutter build apk --release
    # #   - name: Upload artifact to Github
    # #     uses: actions/upload-artifact@v1
    # #     with:
    # #       name: release-apk
    # #       path: build/app/outputs/apk/release/app-release.apk
